### ISSUE TITLE
Adding JQuery to the View Editor config

### ISSUE THREAD

**Issue by hvpatel328** [Open-MBEE/exec-ve#224]
We want to add JQuery to the View Editor configuration so that other webhosted tools can integrate with View Editor better (in this case the JIRA issue collector macro has a dependency on JQuery and we want users to be able to submit a JIRA ticket without leaving View Editor through this macro). Can this be in the default configuration?

**Comment by dlamoris** [comment]
Jquery is already pulled into ve, closing this in favor of a customization issue instead, but will need to assess more first since a jira issue collector may require allowing custom js in customization
